### PR TITLE
Descriptor API tweaks

### PR DESCRIPTION
**Pull request by martinling**
This PR collects followup changes that build on the descriptor API work from #126.

Key changes are:
- Descriptors attached to endpoints are now instantiated (replaces #139)
- The `instantiate_subordinates` function is redesigned to avoid silent dropping of subordinates with duplicate identifiers (replaces #140).
- Orderings of declaration/insertion of subordinates are preserved, allowing control of ordering in binary configurations.
- Fixes to convert some fields to the right types in `from_binary_descriptor` methods.
- A dictionary of known strings and their indexes may be passed to `from_binary_descriptor` methods.
- The `number` field of `USBDescriptor` is made optional, as it is not required for descriptors attached in a configuration.
- The `type_number` field will now be inferred from the `raw` bytes if not otherwise specified.
- Add `@include_in_config` and `@requestable(number=N)` decorators for use on declared descriptor classes.
- Add docstrings for all `USBDescriptor` fields.

### CODE REVIEW

**Review by antoinevg — CHANGES_REQUESTED** [review]
### Works on Windows, Mac and Linux:

* `python -m unittest`
* `python examples/ftdi-echo.py`
* `python examples/rubber-ducky.py`
* `python examples/mass-storage.py`

### Fails:

* `python examples/proxy.py`

```sh
INFO    | __init__       | Starting emulation, press 'Control-C' to disconnect and exit.
INFO    | greatdancer    | Skipping GreatFET-based devices, as the greatfet python module isn't installed.
INFO    | moondancer     | Using the Moondancer backend.
INFO    | moondancer     | Connected HIGH speed device 'facedancer.proxy.USBProxyDevice' to target host.
INFO    | device         | Host issued a bus reset; resetting our connection.
INFO    | moondancer     | Disconnecting from target host.
Traceback (most recent call last):
  File "./examples/usbproxy.py", line 29, in <module>
    main(proxy)
  File "/home/antoine/GreatScott/facedancer.git.upstream/facedancer/devices/__init__.py", line 44, in default_main
    device.emulate(*coroutines)
  File "/home/antoine/GreatScott/facedancer.git.upstream/facedancer/device.py", line 268, in emulate
    self.run_with(*coroutines)
  File "/home/antoine/GreatScott/facedancer.git.upstream/facedancer/device.py", line 253, in run_with
    asyncio.run(inner())
  File "/home/antoine/.pyenv/versions/3.8.20/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/antoine/.pyenv/versions/3.8.20/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/antoine/GreatScott/facedancer.git.upstream/facedancer/device.py", line 251, in inner
    await asyncio.gather(self.run(), *coroutines)
  File "/home/antoine/GreatScott/facedancer.git.upstream/facedancer/device.py", line 240, in run
    self.backend.service_irqs()
  File "/home/antoine/GreatScott/facedancer.git.upstream/facedancer/backends/moondancer.py", line 446, in service_irqs
    self.handle_receive_control(event.endpoint_number)
  File "/home/antoine/GreatScott/facedancer.git.upstream/facedancer/backends/moondancer.py", line 515, in handle_receive_control
    self.connected_device.handle_request(request)
  File "/home/antoine/GreatScott/facedancer.git.upstream/facedancer/proxy.py", line 133, in handle_request
    self._proxy_in_control_request(request)
  File "/home/antoine/GreatScott/facedancer.git.upstream/facedancer/proxy.py", line 240, in _proxy_in_control_request
    request, data, stalled = f.filter_control_in(request, data, stalled)
  File "/home/antoine/GreatScott/facedancer.git.upstream/facedancer/filters/standard.py", line 56, in filter_control_in
    device = USBDescribable.from_binary_descriptor(data)
  File "/home/antoine/GreatScott/facedancer.git.upstream/facedancer/descriptor.py", line 58, in from_binary_descriptor
    return subclass.from_binary_descriptor(data, strings=strings)
  File "/home/antoine/GreatScott/facedancer.git.upstream/facedancer/device.py", line 130, in from_binary_descriptor
    manufacturer_string=lookup(manufacturer_string_index),
  File "/home/antoine/GreatScott/facedancer.git.upstream/facedancer/device.py", line 120, in lookup
    raise Exception(
Exception: Missing string for string descriptor #1
```

This is an interesting edge-case: Basically, when `filters/standard.py` does `device = USBDescribable.from_binary_descriptor(data)` it does not have (nor will it ever have) string descriptors as those requests are simply being forwarded to the proxied device.

**Comment by martinling** [comment]
> This is an interesting edge-case: Basically, when `filters/standard.py` does `device = USBDescribable.from_binary_descriptor(data)` it does not have (nor will it ever have) string descriptors as those requests are simply being forwarded to the proxied device.

Right, yeah.

We can build up some knowledge of the proxied device's string descriptors because the host will almost always request some or all of them at enumeration, and we can monitor those the standard filters and retain the responses.

But that (a) won't give us all of them because some hosts don't ask, and (b) won't give us them at the time when we first need to construct a `USBDevice`. That happens when the host gets the device descriptor, which is the very first request after setting the address.

I thought about that problem and came up with two different solutions:

### Placeholders

When a string is not included in the dict passed to `from_binary_descriptor`, substitute a placeholder like `Unknown String Descriptor #1`.

I'd suggest we make that behaviour optional, and enable it with an extra keyword argument, because in the case where a user is trying to construct a device from captured data, I think it's it's helpful to give an error to tell them that they're missing a string.

The standard filters could then create the device with the placeholder strings, and fill in the actual strings later - if and when they are fetched from the proxied device. The host would never see the placeholders, because if the host requests them, the proxy would just forward the request, get the actual string, and update our records in the process.

### On-demand 

Support passing a helper function to `from_binary_descriptor` which looks up strings on demand.

In the case of the proxy, we'd need to pass a function that requests the string descriptor from the proxied device.

So when we see a descriptor with string references, we'd immediately resolve all of those with additional requests to the proxied device before proceeding further.

### But...

...then I took another look at `filters/standard.py` and realised that it's not even *retaining* the `USBDevice` that it creates from the binary descriptor. All that code is doing is patching the max EP0 packet size and then passing along the modified binary data.

You could get the same effect, at the cost of readability, with:
```diff
             if descriptor_type == self.DESCRIPTOR_DEVICE and req.length >= 7:
                 # Patch our data to overwrite the maximum packet size on EP0.
                 # See USBProxy.connect for a rationale on this.
-                device = USBDescribable.from_binary_descriptor(data)
-                device.max_packet_size_ep0 = 64
-                data = bytearray(device.get_descriptor())[:len(data)]
+                data[7] = 64
                 if self.verbose > 0:
                     log.info("-- Patched device descriptor. --")
```

I went looking for other places that we call `from_binary_descriptor`, and there's only two, both in `FacedancerUSBHost` in `facedancer/core.py`. Both of which seem to similarly assume that it's possible to just round-trip the conversion without any context for the string descriptor numbers.

So I'm not really sure what to do.

**Comment by martinling** [comment]
> re: extra keyword arg -- is it possible to just pass `strings=None` rather than a separate arg or is that case already used for something else?

I don't think that's currently used for anything else. I've used `strings={}` as the default, which avoids having to check whether to attempt the lookup or not.

**Comment by martinling** [comment]
Some thoughts:

The ideal solution to me would be if we'd never allowed `str` fields in `USBDescribable` subclasses in the first place, only ever stored string indices, and left it up to code _using_ the descriptor to decide how to handle string lookups where necessary. Particularly because sometimes, as in the above descriptor-patching snippet, it's not necessary to resolve them at all!

We've discussed changing that, but it's too late to move away from `str` without breaking lots of existing code, and it doesn't seem like a big enough issue to be worth an API-breaking version bump over.

But I'm wondering whether we could switch to `str | int | None` as the type for string fields.

In practice, for any given field that is represented by a string descriptor index, we may know:
1. The string, but not its index (e.g. where we are going to auto-allocate or lookup the index).
2. The index, but not its string (e.g. where we are just doing a round-trip conversion without caring what the indices mean).
3. Both the index and the string.
4. That there is no string.

Using `str | int | None` clearly addresses cases 1, 2 and 4. It doesn't _directly_ address case 3. But in case 3, I think it's always going to be the case that we have the mapping stored _somewhere_ else, so it's OK to use _either_ `str` or `int` because we can always look up the other.

This is actually kind of what we were already doing - if you look at [92e506c](https://github.com/greatscottgadgets/facedancer/pull/141/commits/92e506cbb3855bb1e2a8f305cfb024ee5a3c4b2d), before I added the `strings` parameter to `from_binary_descriptor`, it would just leave `int` values in those fields instead, which is why the round trip conversion in `filters/standard.py` worked before.

So maybe all we need to do is make it official, and change the type to `str | int | None` on all those fields.

**Comment by martinling** [comment]
...the key benefit being that we could then round-trip from a device to generated declarative code and back, without losing the specific string descriptor mappings needed to exactly emulate an existing device.

**Comment by antoinevg** [comment]
100% -- `str | int | (int, str) | None` it is.

**Comment by antoinevg** [comment]
(And once we're on Python 3.10 and have structural pattern matching we can even implement this as an Algebraic Data Type!)

**Comment by martinling** [comment]
Further changes made as follows:

- A new metaclass is used for `USBDescribable` which automates the use of `dataclass`, and automatically inherits the type annotations from the parent class. This avoids the need to re-specify all the field types in every subclass, and fixes a major footgun.

- A new `StringRef` class is now used internally as the type for string fields on device, configuration and interface descriptors. This type is automatically constructed from any of `int | str | None | Tuple[int, str]`. Round trip conversions from and to binary descriptors, without known strings, now work correctly again.

**Pull request merged**
